name: Publish Website
on:
  push:
    branches:
      - master
      - integration
jobs:
  Deploy_To_Staging:
    name: Deploy to Staging
    if: ${{ github.ref == 'refs/heads/integration' && github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: integration
          fetch-depth: 2
      - name: Deploy
        # Copy (ftp) only changed files from source git repo to destination using git ftp
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          ftp-server: ${{ secrets.FTP_TEST_HOST }}
          ftp-username: ${{ secrets.FTP_TEST_USER }}
          ftp-password: ${{ secrets.FTP_TEST_PASSWORD }}
  Deploy_To_Production:
    name: Deploy to Production
    if: ${{ github.ref == 'refs/heads/master' && github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 2
      - name: Deploy
        # Copy (ftp) only changed files from source git repo to destination using git ftp
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          ftp-server: ${{ secrets.FTP_HOST }}
          ftp-username: ${{ secrets.FTP_USER }}
          ftp-password: ${{ secrets.FTP_PASSWORD }}
