name: rdg-connect Deployment Workflow
on:
  push:
    branches:
      - master
      - integration
    paths-ignore:
    - 'README.md'
jobs:
  Deploy_To_Staging:
    name: Deploy to Staging
    if: ${{ github.ref == 'refs/heads/integration' && github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: integration
      - name: Deploy
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          ftp-server: ftp://rdg-connect.org/
          ftp-username: gituser-test@rdg-connect.org
          ftp-password: ${{ secrets.FTP_TEST_SECRET }}
  Deploy_To_Production:
    name: Deploy to Production
    if: ${{ github.ref == 'refs/heads/master' && github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Deploy
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          ftp-server: ftp://ftp.rdg-connect.org/
          ftp-username: gituser@rdg-connect.org
          ftp-password: ${{ secrets.FTP_PASSWORD }}
