name: rdg-connect Deployment Workflow
on:
  push:
    branches:
      - master
      - integration
    paths-ignore:
    - 'README.md'
jobs:
  Deploy_To_Staging:
    name: Deploy to Staging
    if: github.ref == 'integration'
    env:
      STAGE_FTP_SERVER: ftp://rdg-connect.org/
      STAGE_FTP_USERNAME: gituser-test@rdg-connect.org
      STAGE_FTP_PASSWORD: ${{ secrets.FTP_TEST_SECRET }}
    run: |
      echo $STAGE_FTP_SERVER $STAGE_FTP_USERNAME $STAGE_FTP_PASSWORD
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@integration
      - name: Check env variables
        run: |
          echo $STAGE_FTP_SERVER $STAGE_FTP_USERNAME $STAGE_FTP_PASSWORD
      - name: Deploy
        run: |
          apt-get update
          apt-get install lftp
          lftp $INPUT_STAGE_FTP_SERVER -u $INPUT_STAGE_FTP_USERNAME,$INPUT_STAGE_FTP_PASSWORD -e "set ftp:ssl-force false; set ssl:verify-certificate false; mirror --reverse --continue --dereference -x ^\.git/$ $INPUT_LOCALDIR $INPUT_REMOTEDIR; quit"
